language: ruby
install:
- sudo add-apt-repository ppa:texlive-backports/ppa -y
- sudo apt-get update -y
- sudo apt-get install texlive-latex-extra texlive-luatex texlive-fonts-extra latexmk
- gem install travis
- wget http://tug.org/fonts/getnonfreefonts/install-getnonfreefonts
- sudo texlua install-getnonfreefonts
- sudo getnonfreefonts-sys garamond
script: latexmk -pdfps cv.tex
after_success:
- ./.utilities/travis_deploy.sh
- travis restart -r johntfoster/johntfoster-professional-website --token ${TRAVIS_TOKEN}
  --skip-completion-check
env:
  global:
    secure: i9Af1WpHTucCEpNF02P+aOsx6Z18mMtYV5VvMQSvAbg4mHWe9FVj44baJ3bjY0GCHbCJIM+9A0PGCVB/VOjawh4fIaWOPTwQ/K0jyPW3Jrr0TrHiPHzzJ8EClt9W+Ka3ddP2k8dx7PrvON+COiqYngp0k4GGVgV/rOhKHozRzQ4=
